esphome:
  name: garage-temp
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: "badkitty"
  password: "fuzzytreemonitor"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "test_fallback"
    password: "test_fallback"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "my secure password"

ota:
  password: "my secure password"


dallas:
  - pin: D0
    update_interval: 1s

sensor:
  - platform: dallas
    index: 0
    name: "Garage Temperature"
    id: temp
  - platform: wifi_signal
    name: "Garage wifi signal"
    update_interval: 1s
    id: wifi_sig
    entity_category: "diagnostic"

i2c:
    sda: D6
    scl: D7

font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: big
    size: 30
  - file: "gfonts://Roboto"
    id: medium
    size: 20
  - file: "gfonts://Roboto"
    id: small
    size: 10

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3D
    lambda: |-
       it.printf(0, 0, id(big), "%.1f°F", (id(temp).state*9/5)+32);
       it.printf(0, 35, id(medium), "WiFI: %.1f", id(wifi_sig).state);



